# Generated by Django 5.0.1 on 2024-01-26 15:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mains', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 26, 21, 43, 56, 309870, tzinfo=datetime.timezone.utc)),
        ),
    ]
