# Generated by Django 5.0.1 on 2024-01-27 11:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mains', '0003_icecream_alter_product_options_alter_product_publish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 27, 17, 58, 17, 207478, tzinfo=datetime.timezone.utc)),
        ),
    ]
