# Generated by Django 5.0.1 on 2024-01-29 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mains', '0009_alter_product_publish'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='publish',
        ),
        migrations.RemoveField(
            model_name='product',
            name='updated',
        ),
    ]
