# Generated by Django 5.0.1 on 2024-02-03 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mains', '0010_remove_product_publish_remove_product_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='icecream',
            name='slug',
            field=models.SlugField(default='', max_length=255),
        ),
    ]
