# Generated by Django 5.0.1 on 2024-02-03 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mains', '0011_icecream_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='icecream',
            name='price',
            field=models.IntegerField(default=1),
        ),
    ]
